<?php

namespace Admin\AdminBundle\Repository;
use Doctrine\ORM\Query\ResultSetMapping;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * AcaoOrcamentariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcaoOrcamentariaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * lista os anos de exercicio existentes na TB_ACAO_ORCAMENTARIA
     * @return array
     */
    public function listarAnoExercicio(){

        $rs = $this->createQueryBuilder('a')
            ->select('distinct a.nuAnoExercicio')
            ->where('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('stRegistroAtivo', 'S')
            ->orderBy('a.nuAnoExercicio', 'desc')
            ->getQuery()
            ->getResult();

        return $rs;
    }

    public function listarAcaoOrcamentaria($nuAnoExercicio){

        $rs = $this->createQueryBuilder('a')
            ->andWhere('a.nuAnoExercicio = :nuAnoExercicio')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('nuAnoExercicio', $nuAnoExercicio)
            ->setParameter('stRegistroAtivo', 'S')
            ->getQuery()
            ->getResult();

        return $rs;
    }

    public function acaoOrcamentariaId($id){

        $rs = $this->createQueryBuilder('a')
            ->select('
                a.id, a.coTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel, a.vlDespesaEmpenhada,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga,
                b.dsTipoDespesa, c.dsDepartamento, c.sgDepartamento,
                nvl(a.vlAtualizado, 0) - sum(nvl(d.vlExecutarExercicio, 0)) as vlSaldo,
                sum(nvl(d.vlProcessadoCgpo, 0)) as vlProcessadoCgpo,
                sum(nvl(d.vlExecutarExercicio, 0)) as vlAtividade,
                count(d.id) as qtAtividade
            ')
            ->innerJoin('Admin\AdminBundle\Entity\TipoDespesa', 'b', 'WITH', 'b.id = a.coTipoDespesa and b.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\Departamento', 'c', 'WITH', 'c.id = a.coDepartamento and c.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Planodeuso\AtividadeBundle\Entity\AtividadePlanoUso', 'd', 'WITH', 'd.coAcaoOrcamentaria = a.id and d.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere('a.id = :id')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('id', $id)
            ->setParameter('stRegistroAtivo', 'S')
            ->groupBy('
                a.id, a.coTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel, a.vlDespesaEmpenhada,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga,
                b.dsTipoDespesa, c.dsDepartamento, c.sgDepartamento
            ')
            ->getQuery()
            ->getOneOrNullResult();

        return $rs;
    }


    public function jsonListarAcaoOrcamentaria($nuAnoExercicio){
        $sql = '
                SELECT
                    acao.CO_SEQ_ACAO_ORCAMENTARIA AS "id",
                    acao.CO_TIPO_DESPESA AS "coTipoDespesa",
                    acao.CO_DEPARTAMENTO AS "coDepartamento",
                    acao.NU_ANO_EXERCICIO AS "nuAnoExercicio",
                    acao.NU_ACAO_ORCAMENTARIA AS "nuAcaoOrcamentaria",
                    acao.NU_PLANO_ORCAMENTARIO AS "nuPlanoOrcamentario",
                    acao.DS_DENOMINACAO AS "dsDenominacao",
                    acao.VL_EXECUT_EXERCICIO_ANTERIOR AS "vlExecutExercicioAnterior",
                    acao.VL_APROVADO AS "vlAprovado",
                    acao.VL_BLOQUEADO AS "vlBloqueado",
                    acao.VL_ATUALIZADO AS "vlAtualizado",
                    acao.VL_CAPITAL AS "vlCapital",
                    acao.VL_DISPONIVEL AS "vlDiponivel",
                    acao.VL_DESPESA_EMPENHADA AS "vlDespesaEmpenhada",
                    acao.VL_DEPESA_EMPENHADA_ALIQUIDAR AS "vlDepesaEmpenhadaAliquidar",
                    acao.VL_DESPESA_LIQUIDADA AS "vlDespesaLiquidada",
                    acao.VL_DESPESA_PAGA AS "vlDespesaPaga",
                    tpDespesa.DS_TIPO_DESPESA AS "dsTipoDespesa",
                    departamento.DS_DEPARTAMENTO AS "dsDepartamento",
                    departamento.SG_DEPARTAMENTO AS "sgDepartamento",
                    NVL(acao.VL_ATUALIZADO, 0) - NVL(atividade.VL_EXECUTAR_EXERCICIO, 0) AS "vlSaldo",
                    NVL(atividade.QT_ATIVIDADE, 0) AS "qtAtividade",
                    atividade.VL_PROCESSADO_CGPO AS "vlProcessadoCgpo",
                    LISTAGG(departamento2.SG_DEPARTAMENTO, \'; \') WITHIN GROUP (ORDER BY departamento2.SG_DEPARTAMENTO ASC)  AS "sgDepartamentoVinculado"
                FROM
                    DBPROPOSTASAS.TB_ACAO_ORCAMENTARIA acao
                    INNER JOIN DBPROPOSTASAS.TB_TIPO_DESPESA tpDespesa ON (tpDespesa.CO_SEQ_TIPO_DESPESA = acao.CO_TIPO_DESPESA AND tpDespesa.ST_REGISTRO_ATIVO   = :stRegistroAtivo)
                    LEFT JOIN DBPROPOSTASAS.TB_DEPARTAMENTO departamento ON (departamento.CO_SEQ_DEPARTAMENTO = acao.CO_DEPARTAMENTO AND departamento.ST_REGISTRO_ATIVO   = :stRegistroAtivo)
                    LEFT JOIN DBPROPOSTASAS.RL_ACAOORCAMENTAR_DEPARTAMENTO rlacaodep ON (rlacaodep.CO_ACAO_ORCAMENTARIA = acao.CO_SEQ_ACAO_ORCAMENTARIA AND rlacaodep.ST_REGISTRO_ATIVO    = :stRegistroAtivo)
                    LEFT JOIN DBPROPOSTASAS.TB_DEPARTAMENTO departamento2 ON (departamento2.CO_SEQ_DEPARTAMENTO = rlacaodep.CO_DEPARTAMENTO AND departamento2.ST_REGISTRO_ATIVO   = :stRegistroAtivo)
                    LEFT JOIN (
                        SELECT
                            CO_ACAO_ORCAMENTARIA, COUNT(CO_SEQ_ATIVIDADE_PLANOUSO) AS QT_ATIVIDADE, SUM(NVL(VL_EXECUTAR_EXERCICIO, 0)) AS VL_EXECUTAR_EXERCICIO, SUM(NVL(VL_PROCESSADO_CGPO, 0)) AS VL_PROCESSADO_CGPO
                        FROM
                            DBPROPOSTASAS.TB_ATIVIDADE_PLANOUSO
                        WHERE
                            ST_REGISTRO_ATIVO = :stRegistroAtivo AND NU_ANO_EXERCICIO = :nuAnoExercicio
                        GROUP BY
                            CO_ACAO_ORCAMENTARIA
                    ) atividade ON (atividade.CO_ACAO_ORCAMENTARIA = acao.CO_SEQ_ACAO_ORCAMENTARIA)
                    WHERE
                      acao.NU_ANO_EXERCICIO  = :nuAnoExercicio AND acao.ST_REGISTRO_ATIVO   = :stRegistroAtivo
                GROUP BY
                    acao.CO_SEQ_ACAO_ORCAMENTARIA,
                    acao.CO_TIPO_DESPESA,
                    acao.CO_DEPARTAMENTO,
                    acao.NU_ANO_EXERCICIO,
                    acao.NU_ACAO_ORCAMENTARIA,
                    acao.NU_PLANO_ORCAMENTARIO,
                    acao.DS_DENOMINACAO,
                    acao.VL_EXECUT_EXERCICIO_ANTERIOR,
                    acao.VL_APROVADO,
                    acao.VL_BLOQUEADO,
                    acao.VL_ATUALIZADO,
                    acao.VL_CAPITAL,
                    acao.VL_DISPONIVEL,
                    acao.VL_DESPESA_EMPENHADA,
                    acao.VL_DEPESA_EMPENHADA_ALIQUIDAR,
                    acao.VL_DESPESA_LIQUIDADA,
                    acao.VL_DESPESA_PAGA,
                    tpDespesa.DS_TIPO_DESPESA,
                    departamento.DS_DEPARTAMENTO,
                    departamento.SG_DEPARTAMENTO,
                    atividade.VL_EXECUTAR_EXERCICIO,
                    atividade.QT_ATIVIDADE,
                    atividade.VL_PROCESSADO_CGPO
                ORDER BY
                    acao.NU_ACAO_ORCAMENTARIA ASC,
                    acao.NU_PLANO_ORCAMENTARIO ASC,
                    departamento.SG_DEPARTAMENTO ASC';

        $em = $this->getEntityManager();

        $query = $em->getConnection()->executeQuery($sql, array('stRegistroAtivo' => 'S', 'nuAnoExercicio' => $nuAnoExercicio));

        return $query->fetchAll();
    }

    /**
     * Lista somente as ações com atividades registradas
     * @param $nuAnoExercicio
     * @return array
     */
    public function jsonListarAcaoComAtividade($nuAnoExercicio){

        $sql = '
                SELECT
                    acao.CO_SEQ_ACAO_ORCAMENTARIA AS "id",
                    acao.CO_TIPO_DESPESA AS "coTipoDespesa",
                    acao.CO_DEPARTAMENTO AS "coDepartamento",
                    acao.NU_ANO_EXERCICIO AS "nuAnoExercicio",
                    acao.NU_ACAO_ORCAMENTARIA AS "nuAcaoOrcamentaria",
                    acao.NU_PLANO_ORCAMENTARIO AS "nuPlanoOrcamentario",
                    acao.DS_DENOMINACAO AS "dsDenominacao",
                    acao.VL_EXECUT_EXERCICIO_ANTERIOR AS "vlExecutExercicioAnterior",
                    acao.VL_APROVADO AS "vlAprovado",
                    acao.VL_BLOQUEADO AS "vlBloqueado",
                    acao.VL_ATUALIZADO AS "vlAtualizado",
                    acao.VL_CAPITAL AS "vlCapital",
                    acao.VL_DISPONIVEL AS "vlDiponivel",
                    acao.VL_DESPESA_EMPENHADA AS "vlDespesaEmpenhada",
                    acao.VL_DEPESA_EMPENHADA_ALIQUIDAR AS "vlDepesaEmpenhadaAliquidar",
                    acao.VL_DESPESA_LIQUIDADA AS "vlDespesaLiquidada",
                    acao.VL_DESPESA_PAGA AS "vlDespesaPaga",
                    tpDespesa.DS_TIPO_DESPESA AS "dsTipoDespesa",
                    departamento.DS_DEPARTAMENTO AS "dsDepartamento",
                    departamento.SG_DEPARTAMENTO AS "sgDepartamento",
                    NVL(acao.VL_ATUALIZADO, 0) - NVL(atividade.VL_EXECUTAR_EXERCICIO, 0) AS "vlSaldo",
                    NVL(atividade.QT_ATIVIDADE, 0) AS "qtAtividade",
                    atividade.VL_PROCESSADO_CGPO AS "vlProcessadoCgpo",
                    LISTAGG(departamento2.SG_DEPARTAMENTO, \'; \') WITHIN GROUP (ORDER BY departamento2.SG_DEPARTAMENTO ASC)  AS "sgDepartamentoVinculado"
                FROM
                    DBPROPOSTASAS.TB_ACAO_ORCAMENTARIA acao
                    INNER JOIN DBPROPOSTASAS.TB_TIPO_DESPESA tpDespesa ON (tpDespesa.CO_SEQ_TIPO_DESPESA = acao.CO_TIPO_DESPESA AND tpDespesa.ST_REGISTRO_ATIVO   = :stRegistroAtivo)
                    LEFT JOIN DBPROPOSTASAS.TB_DEPARTAMENTO departamento ON (departamento.CO_SEQ_DEPARTAMENTO = acao.CO_DEPARTAMENTO AND departamento.ST_REGISTRO_ATIVO   = :stRegistroAtivo)
                    LEFT JOIN DBPROPOSTASAS.RL_ACAOORCAMENTAR_DEPARTAMENTO rlacaodep ON (rlacaodep.CO_ACAO_ORCAMENTARIA = acao.CO_SEQ_ACAO_ORCAMENTARIA AND rlacaodep.ST_REGISTRO_ATIVO    = :stRegistroAtivo)
                    LEFT JOIN DBPROPOSTASAS.TB_DEPARTAMENTO departamento2 ON (departamento2.CO_SEQ_DEPARTAMENTO = rlacaodep.CO_DEPARTAMENTO AND departamento2.ST_REGISTRO_ATIVO   = :stRegistroAtivo)
                    INNER JOIN (
                        SELECT
                            CO_ACAO_ORCAMENTARIA, COUNT(CO_SEQ_ATIVIDADE_PLANOUSO) AS QT_ATIVIDADE, SUM(NVL(VL_EXECUTAR_EXERCICIO, 0)) AS VL_EXECUTAR_EXERCICIO, SUM(NVL(VL_PROCESSADO_CGPO, 0)) AS VL_PROCESSADO_CGPO
                        FROM
                            DBPROPOSTASAS.TB_ATIVIDADE_PLANOUSO
                        WHERE
                            ST_REGISTRO_ATIVO = :stRegistroAtivo AND NU_ANO_EXERCICIO = :nuAnoExercicio
                        GROUP BY
                            CO_ACAO_ORCAMENTARIA
                    ) atividade ON (atividade.CO_ACAO_ORCAMENTARIA = acao.CO_SEQ_ACAO_ORCAMENTARIA)
                    WHERE
                      acao.NU_ANO_EXERCICIO  = :nuAnoExercicio AND acao.ST_REGISTRO_ATIVO   = :stRegistroAtivo
                GROUP BY
                    acao.CO_SEQ_ACAO_ORCAMENTARIA,
                    acao.CO_TIPO_DESPESA,
                    acao.CO_DEPARTAMENTO,
                    acao.NU_ANO_EXERCICIO,
                    acao.NU_ACAO_ORCAMENTARIA,
                    acao.NU_PLANO_ORCAMENTARIO,
                    acao.DS_DENOMINACAO,
                    acao.VL_EXECUT_EXERCICIO_ANTERIOR,
                    acao.VL_APROVADO,
                    acao.VL_BLOQUEADO,
                    acao.VL_ATUALIZADO,
                    acao.VL_CAPITAL,
                    acao.VL_DISPONIVEL,
                    acao.VL_DESPESA_EMPENHADA,
                    acao.VL_DEPESA_EMPENHADA_ALIQUIDAR,
                    acao.VL_DESPESA_LIQUIDADA,
                    acao.VL_DESPESA_PAGA,
                    tpDespesa.DS_TIPO_DESPESA,
                    departamento.DS_DEPARTAMENTO,
                    departamento.SG_DEPARTAMENTO,
                    atividade.VL_EXECUTAR_EXERCICIO,
                    atividade.QT_ATIVIDADE,
                    atividade.VL_PROCESSADO_CGPO
                ORDER BY
                    acao.NU_ACAO_ORCAMENTARIA ASC,
                    acao.NU_PLANO_ORCAMENTARIO ASC,
                    departamento.SG_DEPARTAMENTO ASC';

        $em = $this->getEntityManager();

        $rs = $em->getConnection()->executeQuery($sql, array('stRegistroAtivo' => 'S', 'nuAnoExercicio' => $nuAnoExercicio));

        return $rs;
    }

    public function relatorioPorAcao($nuAnoExercicio){

        $rs = $this->createQueryBuilder('a')
            ->select("
                a.id, a.coTipoDespesa, b.dsTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao, a.vlDespesaEmpenhada,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga, d.sgDepartamento,
                GREATEST(nvl(a.vlDespesaEmpenhada, 0), nvl(a.vlDespesaEmpenhadaAliquidar, 0), nvl(a.vlDepesaEmpenhadaLiquidada, 0)) as vlEmpenhado,
                COUNT(c.id) as qtAtividade,
                nvl(SUM(c.vlExecutarExercicio), 0) as vlAtividade,
                a.vlAtualizado - SUM(nvl(c.vlExecutarExercicio, 0)) as vlSaldoAcao,
                SUM(nvl(c.vlProcessadoCgpo, 0)) as vlProcessadoCgpo
                
            ")
            ->leftJoin('Admin\AdminBundle\Entity\TipoDespesa', 'b', 'WITH', 'b.id = a.coTipoDespesa and b.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\AtividadePlanoUso', 'c', 'WITH', 'c.coAcaoOrcamentaria = a.id and c.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\Departamento', 'd', 'WITH', 'd.id = a.coDepartamento and a.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere('a.nuAnoExercicio = :nuAnoExercicio')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('nuAnoExercicio', $nuAnoExercicio)
            ->setParameter('stRegistroAtivo', 'S')
            ->groupBy('
                a.id, a.coTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel, a.vlDespesaEmpenhada,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga,
                b.dsTipoDespesa
            ')
            ->groupBy('
                a.id, a.coTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao, d.sgDepartamento,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel, a.vlDespesaEmpenhada,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga, b.dsTipoDespesa
            ')
            ->orderBy('a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario')
            ->getQuery()
            ->getArrayResult();

        return $rs;
    }

    public function relatorioPorAcaoDepartamento($nuAnoExercicio, $coDepartamento){

        $rs = $this->createQueryBuilder('a')
            ->select("
                a.id, a.coTipoDespesa, b.dsTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel, a.vlDespesaEmpenhada,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga,
                GREATEST(nvl(a.vlDespesaEmpenhada, 0), nvl(a.vlDespesaEmpenhadaAliquidar, 0), nvl(a.vlDepesaEmpenhadaLiquidada, 0)) as vlEmpenhado,
                COUNT(c.id) as qtAtividade,
                nvl(SUM(c.vlExecutarExercicio), 0) as vlAtividade,
                a.vlAtualizado - SUM(nvl(c.vlExecutarExercicio, 0)) as vlSaldoAcao,
                SUM(nvl(c.vlProcessadoCgpo, 0)) as vlProcessadoCgpo
            ")
            ->leftJoin('Admin\AdminBundle\Entity\TipoDespesa', 'b', 'WITH', 'b.id = a.coTipoDespesa and b.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\AtividadePlanoUso', 'c', 'WITH', 'c.coAcaoOrcamentaria = a.id and c.coDepartamento = :coDepartamento and c.stRegistroAtivo = :stRegistroAtivo')
            ->innerJoin('Admin\AdminBundle\Entity\RlAcaoOrcamentariaDepartamento', 'd', 'WITH', 'd.coAcaoOrcamentaria = a.id and d.coDepartamento = :coDepartamento and d.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere('a.nuAnoExercicio = :nuAnoExercicio')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('nuAnoExercicio', $nuAnoExercicio)
            ->setParameter('coDepartamento', $coDepartamento)
            ->setParameter('stRegistroAtivo', 'S')
            ->groupBy('
                a.id, a.coTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel, a.vlDespesaEmpenhada,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga,
                b.dsTipoDespesa
            ')
            ->groupBy('
                a.id, a.coTipoDespesa, a.coDepartamento, a.nuAnoExercicio, a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario, a.dsDenominacao,
                a.vlExecutadoExercicioAnterior, a.vlAprovado, a.vlBloqueado, a.vlAtualizado, a.vlCapital, a.vlDisponivel, a.vlDespesaEmpenhada,
                a.vlDespesaEmpenhadaAliquidar, a.vlDepesaEmpenhadaLiquidada, a.vlDespesaPaga, b.dsTipoDespesa
            ')
            ->orderBy('a.nuAcaoOrcamentaria, a.nuPlanoOrcamentario')
            ->getQuery()
            ->getArrayResult();

        return $rs;
    }
}
