<?php

namespace Admin\AdminBundle\Repository;

/**
 * AtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtividadeRepository extends \Doctrine\ORM\EntityRepository
{
}
