<?php

namespace Admin\AdminBundle\Repository;

/**
 * AuxUsuarioPessoaFisicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuxUsuarioPessoaFisicaRepository extends \Doctrine\ORM\EntityRepository
{
}
