<?php

namespace Admin\AdminBundle\Repository;

/**
 * DepartamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartamentoRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaDepartamento(){
        return $this->createQueryBuilder('a')
            ->select('a.id, a.dsDepartamento, a.sgDepartamento')
            ->where('a.stRegistroAtivo = :stregistroativo')
            ->setParameter('stregistroativo', 'S')
            ->orderBy('a.dsDepartamento')
            ->getQuery()
            ->execute();
    }
}
