<?php

namespace Admin\AdminBundle\Repository;

/**
 * HistoricoPlanilhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricoPlanilhaRepository extends \Doctrine\ORM\EntityRepository
{
    public function listarHistorico(){

        $rs = $this->createQueryBuilder('a')->select(
                "a.nuAnoExercicio, a.noArquivo, a.noPlanilha, decode(a.tpPlanilha, '1', 'Ação Orçamentária', '2', 'Nota de Empenho') as dsTipoPlanilha,
                a.qtRegistro, a.qtRegistroNovo, a.qtRegistroAtualizado, b.noPessoaFisica, a.dtCadastro"
            )
            ->innerJoin('\Admin\AdminBundle\Entity\UsuarioPessoaFisica', 'b', 'WITH', 'b.coUsuario = a.coUsuario and b.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('stRegistroAtivo', 'S')
            ->OrderBy('a.dtCadastro', 'DESC')
            ->getQuery()
            ->getResult();

        return $rs;
    }
}
