<?php

namespace Admin\AdminBundle\Repository;

/**
 * MunicipioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipioRepository extends \Doctrine\ORM\EntityRepository
{
}
