<?php

namespace Admin\AdminBundle\Repository;

/**
 * NotaEmpenhoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaEmpenhoRepository extends \Doctrine\ORM\EntityRepository
{
    public function listarNotaEmpenho($nuAnoExercicio){

        $rs = $this->createQueryBuilder('a')
            ->andWhere('a.nuAnoExercicio = :nuAnoExercicio')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('nuAnoExercicio', $nuAnoExercicio)
            ->setParameter('stRegistroAtivo', 'S')
            ->getQuery()
            ->getResult();

        return $rs;
    }

    public function listaNotaEmpenhoAcao ($nuAcao, $nuPlanoAcao) {

        $qb = $this->createQueryBuilder('z');
        $subQuery = $qb
            ->select("t.coNotaEmpenhoPlanouso")
           ->innerJoin('\Admin\AdminBundle\Entity\RlNotaEmpenhoAtividadePlanouso', "t", "WITH", "
                z.id = t.coNotaEmpenhoPlanouso
                and z.stRegistroAtivo = :stRegistroAtivo
                and z.nuAcaoOrcamentaria = :nuAcaoOrcamentaria
                and z.nuPlanoOrcamentario = :nuPlanoOrcamentario")
            ->andWhere("t.stRegistroAtivo = :stRegistroAtivo");

        $rs = $this->createQueryBuilder('a')
            ->andWhere('a.nuAcaoOrcamentaria = :nuAcaoOrcamentaria')
            ->andWhere('a.nuPlanoOrcamentario = :nuPlanoOrcamentario')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere($qb->expr()->notIn('a.id', $subQuery->getDQL()))
            ->setParameter('stRegistroAtivo', 'S')
            ->setParameter('nuAcaoOrcamentaria', $nuAcao)
            ->setParameter('nuPlanoOrcamentario', $nuPlanoAcao)
            ->orderBy('a.dsNotaEmpenho')
            ->getQuery()
            ->getResult();

        return $rs;

    }
}
