<?php

namespace Admin\AdminBundle\Repository;

/**
 * PerfilAcessoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilAcessoRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaPerfil(){
        return $this->createQueryBuilder('a')
            ->select('a.id, a.dsPerfilAcesso')
            ->where('a.stRegistroAtivo = :stregistroativo')
            ->setParameter('stregistroativo', 'S')
            ->orderBy('a.dsPerfilAcesso')
            ->getQuery()
            ->execute();
    }
}
