<?php

namespace Admin\AdminBundle\Repository;

/**
 * PessoaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PessoaRepository extends \Doctrine\ORM\EntityRepository
{
}
