<?php

namespace Admin\AdminBundle\Repository;

/**
 * PessoaFisicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PessoaFisicaRepository extends \Doctrine\ORM\EntityRepository
{
    public function buscaCPF($cpf){
        return $this->createQueryBuilder('a')
            ->select('d.id, a.id as cpf, b.noPessoa, e.dsPerfilAcesso, f.dsDepartamento, d.dtCadastro, d.dtAtualizacao')
            ->innerJoin('Admin\AdminBundle\Entity\Pessoa', 'b', 'WITH', 'b.id = a.id and b.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\UsuarioPessoaFisica', 'c', 'WITH', 'c.nuCpf = a.id and c.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\Usuario', 'd', 'WITH', 'd.id = c.coUsuario and d.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\PerfilAcesso', 'e', 'WITH', 'e.id = d.coPerfilAcesso and e.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\Departamento', 'f', 'WITH', 'f.id = d.coDepartamento and f.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere('a.id = :nuCpf')
            ->setParameter('nuCpf', $cpf)
            ->setParameter('stRegistroAtivo', 'S')
            ->getQuery()
            ->getOneOrNullResult();

    }

}
