<?php

namespace Admin\AdminBundle\Repository;

/**
 * ProcessamentoAtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessamentoAtividadeRepository extends \Doctrine\ORM\EntityRepository
{
}
