<?php

namespace Admin\AdminBundle\Repository;

/**
 * RedeProgramaPlanoUsoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedeProgramaRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaRedePrograma(){
        return $this->createQueryBuilder('a')
            ->select('a.id, a.dsRedePrograma, a.dtCadastro, a.dtAtualizacao, b.sgDepartamento')
            ->innerJoin('\Admin\AdminBundle\Entity\Departamento', 'b', 'WITH', 'b.id = a.coDepartamento and b.stRegistroAtivo = :stregistroativo')
            ->where('a.stRegistroAtivo = :stregistroativo')
            ->setParameter('stregistroativo', 'S')
            ->addOrderBy('a.sgDepartamento')
            ->orderBy('a.dsRedePrograma')
            ->getQuery()
            ->getResult();
    }
}
