<?php

namespace Admin\AdminBundle\Repository;

/**
 * RlDepartamentoAcaoOrcamentariaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RlAcaoOrcamentariaDepartamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
