<?php

namespace Admin\AdminBundle\Repository;

/**
 * RlNotaEmpenhoAtividadePlanousoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RlNotaEmpenhoAtividadePlanousoRepository extends \Doctrine\ORM\EntityRepository
{
}
