<?php

namespace Admin\AdminBundle\Repository;

/**
 * StatusItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatusItemRepository extends \Doctrine\ORM\EntityRepository
{
}
