<?php

namespace Admin\AdminBundle\Repository;

/**
 * TipoComponenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoComponenteRepository extends \Doctrine\ORM\EntityRepository
{
}
