<?php

namespace Admin\AdminBundle\Repository;

/**
 * TipoAtividadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoAtividadeRepository extends \Doctrine\ORM\EntityRepository
{
}
