<?php

namespace Admin\AdminBundle\Repository;

/**
 * DespesaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDespesaRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaTipoDespesa(){
        return $this->createQueryBuilder('a')
            ->select('a.id, a.dsTipoDespesa')
            ->where('a.stRegistroAtivo = :stregistroativo')
            ->setParameter('stregistroativo', 'S')
            ->getQuery()
            ->execute();
    }
}
