<?php

namespace Admin\AdminBundle\Repository;

/**
 * InstrumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInstrumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
