<?php

namespace Admin\AdminBundle\Repository;

/**
 * UFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UFRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaUfForm(){

        return $this->createQueryBuilder('u')
            ->orderBy("decode(u.id, 'XX', 'A', u.sgUf)"); //Realiza o decode para ordenar o valor XX em primeiro lugar
        ;
    }
}
