<?php

namespace Admin\AdminBundle\Repository;

/**
 * UsuarioRecuperaSenhaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRecuperaSenhaRepository extends \Doctrine\ORM\EntityRepository
{

    public function ultimoToken($coUsuario){
        $dataAtual =  new \DateTime("now", new \DateTimeZone("America/Sao_Paulo"));
        return $this->createQueryBuilder('a')
            ->andWhere('a.coUsuario = :coUsuario')
            ->andWhere('a.dtVencimento >= to_date(:dtAtual, \'YYYY-MM-DD HH24:MI:SS\')')
            ->andWhere('a.stSenhaAlterada = :stSenhaAlterada')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('coUsuario', $coUsuario)
            ->setParameter('dtAtual', $dataAtual->format("Y-m-d H:i:s"))
            ->setParameter('stSenhaAlterada', 'N')
            ->setParameter('stRegistroAtivo', 'S')
            ->orderBy('a.dtVencimento', 'desc')
            ->getQuery()
            ->execute();
    }
}
