<?php

namespace Admin\AdminBundle\Repository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function listaUsuario(){

        return $this->createQueryBuilder('a')
            ->select('a.id, b.nuCpf, b.noPessoaFisica, c.dsPerfilAcesso, d.dsDepartamento, a.dtCadastro, a.dtAtualizacao')
            ->innerJoin('Admin\AdminBundle\Entity\UsuarioPessoaFisica', 'b', 'WITH', 'b.coUsuario = a.id and b.stRegistroAtivo = :stRegistroAtivo')
            ->innerJoin('Admin\AdminBundle\Entity\PerfilAcesso', 'c', 'WITH', 'c.id = a.coPerfilAcesso and c.stRegistroAtivo = :stRegistroAtivo')
            ->leftJoin('Admin\AdminBundle\Entity\Departamento', 'd', 'WITH', 'd.id = a.coDepartamento and d.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere('a.id <> 1')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('stRegistroAtivo', 'S')
            ->orderBy('b.noPessoaFisica')
            ->getQuery()
            ->execute();
    }

    public function encontrarUsuario($usuario){

        return $this->createQueryBuilder('a')
            ->select('a.id, b.nuCpf, b.noPessoaFisica, b.dsEmail, a.dtCadastro, a.dtAtualizacao')
            ->innerJoin('Admin\AdminBundle\Entity\UsuarioPessoaFisica', 'b', 'WITH', 'b.coUsuario = a.id and b.stRegistroAtivo = :stRegistroAtivo')
            ->andWhere('a.dsUsuario = :dsUsuario')
            ->andWhere('a.id <> 1')
            ->andWhere('a.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('dsUsuario', $usuario)
            ->setParameter('stRegistroAtivo', 'S')
            ->getQuery()
            ->getOneOrNullResult();

    }

}
