<?php

namespace Admin\AdminBundle\Repository;

/**
 * UsuarioPessoaFisicaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioPessoaFisicaRepository extends \Doctrine\ORM\EntityRepository
{

    public function listaUsuario(){

        return $this->createQueryBuilder('p')
            ->andWhere('p.stRegistroAtivo = :stRegistroAtivo')
            ->setParameter('stRegistroAtivo', 'S')
            ->innerJoin('p.usuario', 'u')
            ->getQuery()
            ->execute();
    }

}

