<?php

namespace Admin\AdminBundle\Repository;

/**
 * VinculoPlanejamentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VinculoPlanejamentoRepository extends \Doctrine\ORM\EntityRepository
{
}
