<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Validator\Constraints\SaldoValidator' shared autowired service.

return $this->services['AppBundle\Validator\Constraints\SaldoValidator'] = new \AppBundle\Validator\Constraints\SaldoValidator();
