<?php

namespace AppBundle\Repository;

/**
 * UserPFRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPFRepository extends \Doctrine\ORM\EntityRepository
{
}
