<?php

namespace AppBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;


/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
	public function loadUserByUsername($username)
	{
		$rs = $this->createQueryBuilder('u')
			->where('u.user = :username and u.stRegistroAtivo = :stregistroativo')
			->setParameter('username', $username)
			->setParameter('stregistroativo', 'S')
			->getQuery()
			->getOneOrNullResult();
		return $rs;
	}

}
