<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9oh7kei\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9oh7kei/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9oh7kei.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9oh7kei\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9oh7kei\appProdProjectContainer(array(
    'container.build_hash' => '9oh7kei',
    'container.build_id' => '8aa1fb28',
    'container.build_time' => 1552584329,
));
