<?php

namespace Proxies\__CG__\Admin\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UF extends \Admin\AdminBundle\Entity\UF implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'sgUf', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'noUFAcentuado', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'coRegiao', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'noUF', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'stRegistroAtivo'];
        }

        return ['__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'sgUf', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'noUFAcentuado', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'coRegiao', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'noUF', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UF' . "\0" . 'stRegistroAtivo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UF $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSgUf($sgUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSgUf', [$sgUf]);

        return parent::setSgUf($sgUf);
    }

    /**
     * {@inheritDoc}
     */
    public function getSgUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSgUf', []);

        return parent::getSgUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoUFAcentuado($noUFAcentuado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoUFAcentuado', [$noUFAcentuado]);

        return parent::setNoUFAcentuado($noUFAcentuado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoUFAcentuado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoUFAcentuado', []);

        return parent::getNoUFAcentuado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoRegiao($coRegiao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoRegiao', [$coRegiao]);

        return parent::setCoRegiao($coRegiao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoRegiao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoRegiao', []);

        return parent::getCoRegiao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoUF($noUF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoUF', [$noUF]);

        return parent::setNoUF($noUF);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoUF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoUF', []);

        return parent::getNoUF();
    }

    /**
     * {@inheritDoc}
     */
    public function setStRegistroAtivo($stRegistroAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStRegistroAtivo', [$stRegistroAtivo]);

        return parent::setStRegistroAtivo($stRegistroAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStRegistroAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStRegistroAtivo', []);

        return parent::getStRegistroAtivo();
    }

}
