<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Admin\AdminBundle\Form\AtividadeType' shared autowired service.

return $this->services['Admin\AdminBundle\Form\AtividadeType'] = new \Admin\AdminBundle\Form\AtividadeType();
