<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine.dbal.default_connection' shared service.

$a = new \Symfony\Bridge\Doctrine\ContainerAwareEventManager($this);
$a->addEventListener(array(0 => 'postConnect'), new \Doctrine\DBAL\Event\Listeners\OracleSessionInit());
$a->addEventListener(array(0 => 'loadClassMetadata'), ${($_ = isset($this->services['doctrine.orm.default_listeners.attach_entity_listeners']) ? $this->services['doctrine.orm.default_listeners.attach_entity_listeners'] : $this->services['doctrine.orm.default_listeners.attach_entity_listeners'] = new \Doctrine\ORM\Tools\AttachEntityListenersListener()) && false ?: '_'});
$a->addEventListener(array(0 => 'preUpdate'), new \Admin\AdminBundle\EventListener\PreUpdate());

return $this->services['doctrine.dbal.default_connection'] = ${($_ = isset($this->services['doctrine.dbal.connection_factory']) ? $this->services['doctrine.dbal.connection_factory'] : $this->services['doctrine.dbal.connection_factory'] = new \Doctrine\Bundle\DoctrineBundle\ConnectionFactory(array())) && false ?: '_'}->createConnection(array('driver' => 'pdo_oci', 'host' => '', 'port' => '', 'dbname' => '(DESCRIPTION= (LOAD_BALANCE = ON) (FAILOVER = ON) (ADDRESS=(PROTOCOL=TCP)(HOST=srvoradf20-scan.saude.gov)(PORT=1521)) (CONNECT_DATA=(SERVICE_NAME=DFDO1.SAUDE.GOV) (FAILOVER_MODE=(TYPE=SELECT)(METHOD=BASIC)) ))', 'user' => 'PROPOSTASASWEB', 'password' => 'PROPOSTASAS5416722165L29K78', 'charset' => 'UTF8', 'driverOptions' => array(), 'defaultTableOptions' => array()), new \Doctrine\DBAL\Configuration(), $a, array());
