<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Admin\AdminBundle\Controller\DefaultController' shared autowired service.

return $this->services['Admin\AdminBundle\Controller\DefaultController'] = new \Admin\AdminBundle\Controller\DefaultController();
