<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_js_routing.dump_command' shared service.

$this->services['fos_js_routing.dump_command'] = $instance = new \FOS\JsRoutingBundle\Command\DumpCommand(${($_ = isset($this->services['fos_js_routing.extractor']) ? $this->services['fos_js_routing.extractor'] : $this->load(__DIR__.'/getFosJsRouting_ExtractorService.php')) && false ?: '_'}, ${($_ = isset($this->services['fos_js_routing.serializer']) ? $this->services['fos_js_routing.serializer'] : $this->load(__DIR__.'/getFosJsRouting_SerializerService.php')) && false ?: '_'}, 'D:\\planouso\\app', NULL);

$instance->setName('fos:js-routing:dump');

return $instance;
