<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/admin'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CGPO'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/perfil'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CGPO', 2 => 'ROLE_DEPARTAMENTO'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/changepasswd'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_CGPO', 2 => 'ROLE_DEPARTAMENTO'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/atividade'), array(0 => 'ROLE_DEPARTAMENTO'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/relatorio'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_DEPARTAMENTO', 2 => 'ROLE_CGPO', 3 => 'ROLE_LEITOR'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/json'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_DEPARTAMENTO', 2 => 'ROLE_CGPO', 3 => 'ROLE_LEITOR'), NULL);

return $instance;
