<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsxeub1\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsxeub1/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBsxeub1.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBsxeub1\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBsxeub1\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bsxeub1',
    'container.build_id' => '21555b4b',
    'container.build_time' => 1554249976,
));
