<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5q2h7ko\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5q2h7ko/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5q2h7ko.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5q2h7ko\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5q2h7ko\appDevDebugProjectContainer(array(
    'container.build_hash' => '5q2h7ko',
    'container.build_id' => '14ec0171',
    'container.build_time' => 1554768203,
));
