<?php

namespace Proxies\__CG__\Admin\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsuarioPessoaFisica extends \Admin\AdminBundle\Entity\UsuarioPessoaFisica implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'usuario', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'coUsuario', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'noPessoaFisica', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'dsEmail', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'nuDdd', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'nuTelefone', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'nuCpf', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'dtCadastro', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'dtAtualizacao', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'stRegistroAtivo'];
        }

        return ['__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'usuario', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'coUsuario', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'noPessoaFisica', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'dsEmail', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'nuDdd', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'nuTelefone', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'nuCpf', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'dtCadastro', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'dtAtualizacao', '' . "\0" . 'Admin\\AdminBundle\\Entity\\UsuarioPessoaFisica' . "\0" . 'stRegistroAtivo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsuarioPessoaFisica $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoUsuario($coUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoUsuario', [$coUsuario]);

        return parent::setCoUsuario($coUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoUsuario', []);

        return parent::getCoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoPessoaFisica($noPessoaFisica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoPessoaFisica', [$noPessoaFisica]);

        return parent::setNoPessoaFisica($noPessoaFisica);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoPessoaFisica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoPessoaFisica', []);

        return parent::getNoPessoaFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsEmail($dsEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsEmail', [$dsEmail]);

        return parent::setDsEmail($dsEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsEmail', []);

        return parent::getDsEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuDdd($nuDdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuDdd', [$nuDdd]);

        return parent::setNuDdd($nuDdd);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuDdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuDdd', []);

        return parent::getNuDdd();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuTelefone($nuTelefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuTelefone', [$nuTelefone]);

        return parent::setNuTelefone($nuTelefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuTelefone', []);

        return parent::getNuTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuCpf($nuCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuCpf', [$nuCpf]);

        return parent::setNuCpf($nuCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuCpf', []);

        return parent::getNuCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCadastro($dtCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCadastro', [$dtCadastro]);

        return parent::setDtCadastro($dtCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCadastro', []);

        return parent::getDtCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtAtualizacao($dtAtualizacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtAtualizacao', [$dtAtualizacao]);

        return parent::setDtAtualizacao($dtAtualizacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtAtualizacao', []);

        return parent::getDtAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setStRegistroAtivo($stRegistroAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStRegistroAtivo', [$stRegistroAtivo]);

        return parent::setStRegistroAtivo($stRegistroAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStRegistroAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStRegistroAtivo', []);

        return parent::getStRegistroAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

}
