<?php

namespace Proxies\__CG__\Admin\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class HistoricoPlanilha extends \Admin\AdminBundle\Entity\HistoricoPlanilha implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'coUsuario', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'nuAnoExercicio', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'noArquivo', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'noPlanilha', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'tpPlanilha', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'qtRegistro', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'qtRegistroNovo', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'qtRegistroAtualizado', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'dtCadastro', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'stRegistroAtivo'];
        }

        return ['__isInitialized__', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'id', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'coUsuario', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'nuAnoExercicio', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'noArquivo', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'noPlanilha', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'tpPlanilha', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'qtRegistro', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'qtRegistroNovo', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'qtRegistroAtualizado', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'dtCadastro', '' . "\0" . 'Admin\\AdminBundle\\Entity\\HistoricoPlanilha' . "\0" . 'stRegistroAtivo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (HistoricoPlanilha $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoUsuario($coUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoUsuario', [$coUsuario]);

        return parent::setCoUsuario($coUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoUsuario', []);

        return parent::getCoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuAnoExercicio($nuAnoExercicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuAnoExercicio', [$nuAnoExercicio]);

        return parent::setNuAnoExercicio($nuAnoExercicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuAnoExercicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuAnoExercicio', []);

        return parent::getNuAnoExercicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoArquivo($noArquivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoArquivo', [$noArquivo]);

        return parent::setNoArquivo($noArquivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoArquivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoArquivo', []);

        return parent::getNoArquivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoPlanilha($noPlanilha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoPlanilha', [$noPlanilha]);

        return parent::setNoPlanilha($noPlanilha);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoPlanilha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoPlanilha', []);

        return parent::getNoPlanilha();
    }

    /**
     * {@inheritDoc}
     */
    public function setTpPlanilha($tpPlanilha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTpPlanilha', [$tpPlanilha]);

        return parent::setTpPlanilha($tpPlanilha);
    }

    /**
     * {@inheritDoc}
     */
    public function getTpPlanilha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTpPlanilha', []);

        return parent::getTpPlanilha();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtRegistro($qtRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtRegistro', [$qtRegistro]);

        return parent::setQtRegistro($qtRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtRegistro', []);

        return parent::getQtRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtRegistroNovo($qtRegistroNovo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtRegistroNovo', [$qtRegistroNovo]);

        return parent::setQtRegistroNovo($qtRegistroNovo);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtRegistroNovo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtRegistroNovo', []);

        return parent::getQtRegistroNovo();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtRegistroAtualizado($qtRegistroAtualizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtRegistroAtualizado', [$qtRegistroAtualizado]);

        return parent::setQtRegistroAtualizado($qtRegistroAtualizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtRegistroAtualizado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtRegistroAtualizado', []);

        return parent::getQtRegistroAtualizado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCadastro($dtCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCadastro', [$dtCadastro]);

        return parent::setDtCadastro($dtCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCadastro', []);

        return parent::getDtCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setStRegistroAtivo($stRegistroAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStRegistroAtivo', [$stRegistroAtivo]);

        return parent::setStRegistroAtivo($stRegistroAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStRegistroAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStRegistroAtivo', []);

        return parent::getStRegistroAtivo();
    }

}
