<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \AppBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'pessoaFisica', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'perfilAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'updateAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'coPerfilAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'coDepartamento', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dtUltimoAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dsIpUltimoAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'stRegistroAtivo'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'pessoaFisica', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'perfilAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'password', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'updateAt', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'roles', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'coPerfilAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'coDepartamento', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dtUltimoAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'dsIpUltimoAcesso', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'stRegistroAtivo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdateAt($updateAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdateAt', [$updateAt]);

        return parent::setUpdateAt($updateAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdateAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdateAt', []);

        return parent::getUpdateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles($roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoPerfilAcesso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoPerfilAcesso', []);

        return parent::getCoPerfilAcesso();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoPerfilAcesso($coPerfilAcesso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoPerfilAcesso', [$coPerfilAcesso]);

        return parent::setCoPerfilAcesso($coPerfilAcesso);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoDepartamento', []);

        return parent::getCoDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoDepartamento($coDepartamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoDepartamento', [$coDepartamento]);

        return parent::setCoDepartamento($coDepartamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtUltimoAcesso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtUltimoAcesso', []);

        return parent::getDtUltimoAcesso();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtUltimoAcesso($dtUltimoAcesso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtUltimoAcesso', [$dtUltimoAcesso]);

        return parent::setDtUltimoAcesso($dtUltimoAcesso);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsIpUltimoAcesso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsIpUltimoAcesso', []);

        return parent::getDsIpUltimoAcesso();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsIpUltimoAcesso($dsIpUltimoAcesso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsIpUltimoAcesso', [$dsIpUltimoAcesso]);

        return parent::setDsIpUltimoAcesso($dsIpUltimoAcesso);
    }

    /**
     * {@inheritDoc}
     */
    public function getStRegistroAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStRegistroAtivo', []);

        return parent::getStRegistroAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStRegistroAtivo($stRegistroAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStRegistroAtivo', [$stRegistroAtivo]);

        return parent::setStRegistroAtivo($stRegistroAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getPessoaFisica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPessoaFisica', []);

        return parent::getPessoaFisica();
    }

    /**
     * {@inheritDoc}
     */
    public function setPessoaFisica($pessoaFisica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPessoaFisica', [$pessoaFisica]);

        return parent::setPessoaFisica($pessoaFisica);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerfilAcesso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerfilAcesso', []);

        return parent::getPerfilAcesso();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerfilAcesso($perfilAcesso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerfilAcesso', [$perfilAcesso]);

        return parent::setPerfilAcesso($perfilAcesso);
    }

}
